// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncEvent_EventType int32

const (
	SyncEvent_ROOM_UPDATED        SyncEvent_EventType = 0
	SyncEvent_RESERVATION_UPDATED SyncEvent_EventType = 1
	SyncEvent_ROOM_DELETED        SyncEvent_EventType = 2
	SyncEvent_RESERVATION_DELETED SyncEvent_EventType = 3
)

// Enum value maps for SyncEvent_EventType.
var (
	SyncEvent_EventType_name = map[int32]string{
		0: "ROOM_UPDATED",
		1: "RESERVATION_UPDATED",
		2: "ROOM_DELETED",
		3: "RESERVATION_DELETED",
	}
	SyncEvent_EventType_value = map[string]int32{
		"ROOM_UPDATED":        0,
		"RESERVATION_UPDATED": 1,
		"ROOM_DELETED":        2,
		"RESERVATION_DELETED": 3,
	}
)

func (x SyncEvent_EventType) Enum() *SyncEvent_EventType {
	p := new(SyncEvent_EventType)
	*p = x
	return p
}

func (x SyncEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (SyncEvent_EventType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x SyncEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncEvent_EventType.Descriptor instead.
func (SyncEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2, 0}
}

// Representation of a Room update
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Equipments    string                 `protobuf:"bytes,6,opt,name=equipments,proto3" json:"equipments,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Room) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Room) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetEquipments() string {
	if x != nil {
		return x.Equipments
	}
	return ""
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Representation of a Reservation update
type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Reservation) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Reservation) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Reservation) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Reservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// The event sent by the server to the client
type SyncEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     SyncEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=riad.sync.SyncEvent_EventType" json:"type,omitempty"`
	EntityId string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*SyncEvent_Room
	//	*SyncEvent_Reservation
	Data          isSyncEvent_Data `protobuf_oneof:"data"`
	SequenceId    int64            `protobuf:"varint,5,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncEvent) GetType() SyncEvent_EventType {
	if x != nil {
		return x.Type
	}
	return SyncEvent_ROOM_UPDATED
}

func (x *SyncEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SyncEvent) GetData() isSyncEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncEvent) GetRoom() *Room {
	if x != nil {
		if x, ok := x.Data.(*SyncEvent_Room); ok {
			return x.Room
		}
	}
	return nil
}

func (x *SyncEvent) GetReservation() *Reservation {
	if x != nil {
		if x, ok := x.Data.(*SyncEvent_Reservation); ok {
			return x.Reservation
		}
	}
	return nil
}

func (x *SyncEvent) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

type isSyncEvent_Data interface {
	isSyncEvent_Data()
}

type SyncEvent_Room struct {
	Room *Room `protobuf:"bytes,3,opt,name=room,proto3,oneof"`
}

type SyncEvent_Reservation struct {
	Reservation *Reservation `protobuf:"bytes,4,opt,name=reservation,proto3,oneof"`
}

func (*SyncEvent_Room) isSyncEvent_Data() {}

func (*SyncEvent_Reservation) isSyncEvent_Data() {}

// Request to start the synchronization stream
type SyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LastSequenceId int64                  `protobuf:"varint,2,opt,name=last_sequence_id,json=lastSequenceId,proto3" json:"last_sequence_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SyncRequest) GetLastSequenceId() int64 {
	if x != nil {
		return x.LastSequenceId
	}
	return 0
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\triad.sync\"\xb2\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"equipments\x18\x06 \x01(\tR\n" +
	"equipments\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xb9\x01\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xcb\x02\n" +
	"\tSyncEvent\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.riad.sync.SyncEvent.EventTypeR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12%\n" +
	"\x04room\x18\x03 \x01(\v2\x0f.riad.sync.RoomH\x00R\x04room\x12:\n" +
	"\vreservation\x18\x04 \x01(\v2\x16.riad.sync.ReservationH\x00R\vreservation\x12\x1f\n" +
	"\vsequence_id\x18\x05 \x01(\x03R\n" +
	"sequenceId\"a\n" +
	"\tEventType\x12\x10\n" +
	"\fROOM_UPDATED\x10\x00\x12\x17\n" +
	"\x13RESERVATION_UPDATED\x10\x01\x12\x10\n" +
	"\fROOM_DELETED\x10\x02\x12\x17\n" +
	"\x13RESERVATION_DELETED\x10\x03B\x06\n" +
	"\x04data\"M\n" +
	"\vSyncRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12(\n" +
	"\x10last_sequence_id\x18\x02 \x01(\x03R\x0elastSequenceId2N\n" +
	"\vSyncService\x12?\n" +
	"\rStreamUpdates\x12\x16.riad.sync.SyncRequest\x1a\x14.riad.sync.SyncEvent0\x01B.Z,github.com/anomalyco/riad_project/proto/syncb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_proto_goTypes = []any{
	(SyncEvent_EventType)(0), // 0: riad.sync.SyncEvent.EventType
	(*Room)(nil),             // 1: riad.sync.Room
	(*Reservation)(nil),      // 2: riad.sync.Reservation
	(*SyncEvent)(nil),        // 3: riad.sync.SyncEvent
	(*SyncRequest)(nil),      // 4: riad.sync.SyncRequest
}
var file_sync_proto_depIdxs = []int32{
	0, // 0: riad.sync.SyncEvent.type:type_name -> riad.sync.SyncEvent.EventType
	1, // 1: riad.sync.SyncEvent.room:type_name -> riad.sync.Room
	2, // 2: riad.sync.SyncEvent.reservation:type_name -> riad.sync.Reservation
	4, // 3: riad.sync.SyncService.StreamUpdates:input_type -> riad.sync.SyncRequest
	3, // 4: riad.sync.SyncService.StreamUpdates:output_type -> riad.sync.SyncEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_sync_proto_msgTypes[2].OneofWrappers = []any{
		(*SyncEvent_Room)(nil),
		(*SyncEvent_Reservation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
