// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} userID
 * @param {string} roomID
 * @param {string} start
 * @param {string} end
 * @param {number} amount
 * @returns {$CancellablePromise<string>}
 */
export function CreateLocalReservation(userID, roomID, start, end, amount) {
    return $Call.ByID(306295986, userID, roomID, start, end, amount);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetLocalRooms() {
    return $Call.ByID(3732093622).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} table
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetUnsynced(table) {
    return $Call.ByID(1592907366, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} table
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MarkAsSynced(table, id) {
    return $Call.ByID(276821606, table, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(839953470);
}

/**
 * @param {string} id
 * @param {number} num
 * @param {string} roomType
 * @param {number} price
 * @param {string} desc
 * @param {string} equip
 * @param {string} status
 * @returns {$CancellablePromise<void>}
 */
export function UpdateLocalRoom(id, num, roomType, price, desc, equip, status) {
    return $Call.ByID(3510581132, id, num, roomType, price, desc, equip, status);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
